security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Custom\CMSBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: ROLE_ADMIN }
        user_db:
            entity: { class: CustomCMSBundle:User, property: username }
    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTENTICATED_ANONUMOUSLY }
        - { path: /cms/user, roles: IS_AUTENTICATED_ANONUMOUSLY }
        - { path: /.*, roles: IS_AUTENTICATED_ANONUMOUSLY }
